name: On Push

on:  
  push:
    branches:
      - main
    paths-ignore: [ 'Doc/**', 'Flights/**', 'Html/**', 'Images/**', 'Localdoc/**', 'Scenarios/**', 'Textures/**', 'Textures2/**']
  pull_request:
    branches:
      - main
    paths-ignore: [ 'Doc/**', 'Flights/**', 'Html/**', 'Images/**', 'Localdoc/**', 'Scenarios/**', 'Textures/**', 'Textures2/**']

jobs:
  build:
    name: Push
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x64
            os: windows-2022
          - architecture: x86
            os: windows-2022
          - architecture: x64
            os: windows-2022
            sdl3: sdl3
    uses: ./.github/workflows/reusable-build.yml
    with:
      os: ${{ matrix.os }}
      architecture: ${{ matrix.architecture }}
      sdl3: ${{ matrix.sdl3 == 'sdl3' }}
      upload: true
