name: Manual PR Build

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: Build architecture
        required: true
        default: x86
        type: choice
        options:
          - x86
          - x64
      sdl3:
        description: Use SDL3 instead of DirectInput/Win32
        required: false
        default: false
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      os: windows-2022
      architecture: ${{ inputs.architecture }}
      configuration: release
      sdl3: ${{ inputs.sdl3 }}
      upload: true
